### ISSUE TITLE
Do you plan on releasing the weights?

### ISSUE THREAD

**Issue by Njasa2k** [AlonzoLeeeooo/SketchRefiner#1]
Do you plan on releasing the weights?

**Comment by AlonzoLeeeooo** [comment]
Hi @ninjasaid2k ,

Thanks for your attention! We plan to release the pre-trained model weights recently. I will reply you once we upload the model weights.

Best,

**Comment by AlonzoLeeeooo** [comment]
Hi @ninjasaid2k,

We have released our pre-trained model weights on three public datasets, which you may refer to in [here](https://pan.baidu.com/s/1TAqqwHkjnBoDmfxMl0vl6Q?pwd=skre#list/path=%2F).

Hope this answer could help you address your proposed problem!
Best,

**Comment by ninjasaid2k** [comment]
> Hi @ninjasaid2k,
> 
> We have released our pre-trained model weights on three public datasets, which you may refer to in [here](https://pan.baidu.com/s/1TAqqwHkjnBoDmfxMl0vl6Q?pwd=skre#list/path=%2F).
> 
> Hope this answer could help you address your proposed problem! Best,

It seems that link is not working.
