### ISSUE TITLE
关于评价指标问题

### ISSUE THREAD

**Issue by liuna0211** [AlonzoLeeeooo/SketchRefiner#11]
作者您好，我想以这篇论文为基础，做改进发个自己的论文。想问一下评价指标什么的有没有代码，我看论文中有很多对比结果的评价指标。非常感谢您

**Comment by AlonzoLeeeooo** [comment]
下面这些仓库资源你可以参考一下：
- **PSNR、SSIM、FID：** [ZITS Inpainting](https://github.com/DQiaole/ZITS_inpainting)
- **IS：** https://github.com/sbarratt/inception-score-pytorch
- **Style Loss**：[SketchEdit](https://github.com/zengxianyu/sketchedit)

**Comment by AlonzoLeeeooo** [comment]
@liuna0211 您好，关于我们的工作您这边暂时没有其他问题的话，这个issue就先暂时关闭了哈～后续如果您有其他问题，欢迎随时在这个issue底下留言，或者[提出一个新issue](https://github.com/AlonzoLeeeooo/SketchRefiner/issues/new)联系我们～
