### ISSUE TITLE
关于指标问题

### ISSUE THREAD

**Issue by liuna0211** [AlonzoLeeeooo/SketchRefiner#12]
作者您好，我想输出指标，应该是使用测试集，对照的应该是推理部分的代码吗？，我查看推理部分的代码，并没有指标相关的代码。但是训练代码中，如果EVAL_INTERVAL不为0，有对应代码。论文中用于比较的指标，是在EVAL_INTERVAL不为0的情况下生成的吗？我现在不知道如何与其他模型对比指标，因为我无法知道指标。

**Comment by AlonzoLeeeooo** [comment]
1. 对照的应该是推理部分的代码。
2. 关于评测指标计算相关的问题，目前暂时没有现成的代码，我们提供了一些可参考的脚本和GitHub仓库（详见[#11](https://github.com/AlonzoLeeeooo/SketchRefiner/issues/11)），您可以基于这些仓库，根据您实际的推理需求来做少量修改。
3. `EVAL_INTERVAL`不为0的情况中有部分评测指标，可以直接使用，其余指标请参考第二条。
