### ISSUE TITLE
Where can I find the training data？

### ISSUE THREAD

**Issue by HHHH17** [AlonzoLeeeooo/SketchRefiner#2]
Where can I find the training data？

**Comment by AlonzoLeeeooo** [comment]
> Where can I find the training data？

Hi @HHHH17,
We perform our experiments on public datasets, including [CelebA-HQ](https://github.com/tkarras/progressive_growing_of_gans), [Places2](http://places2.csail.mit.edu/download.html), [ImageNet](https://www.image-net.org/). You may refer to their official websites to download the source images.

For mask generation, we employ the free-form mask generator in [DeepFill-v2](https://github.com/JiahuiYu/generative_inpainting).

For sketch simulation, we employ the BDCN edge detector, which you can find their implementation in [here](https://github.com/pkuCactus/BDCN).

If you have any further problem, please feel free to update the issue. Hope the aforementioned information addresses your problem!
Best,
