### ISSUE TITLE
 sketches

### ISSUE THREAD

**Issue by SHIJILIANG01** [AlonzoLeeeooo/SketchRefiner#3]
Hello, thank you for your excellent work! I am very interested in this article. Could you please share the sketches of your trained CelebA-HQ dataset, as it is a bit challenging for me to retrain it? Thank you!

**Comment by AlonzoLeeeooo** [comment]
Hi @SHIJILIANG01 ,

Thanks for your attention of our work! 
We will update the sketch preprocessing scripts ASAP, and will notice you when the code is ready.

Best

**Comment by AlonzoLeeeooo** [comment]
Hi @SHIJILIANG01 ,

We have updated the sketch generation code in `scripts/make_deform_sketch.py`. For detailed usage, you may refer to the instructions in our GitHub repository.

Hope this solution addresses your concern. If you have any difficulties in using the code, please feel free to contact us.

Best
