### ISSUE TITLE
edges_prefix

### ISSUE THREAD

**Issue by LQ971225** [AlonzoLeeeooo/SketchRefiner#4]
Hello, I'm very interested in this article, it's a very good article. Could you please tell me how "edges_prefix" was generated and what it generates?

**Comment by AlonzoLeeeooo** [comment]
Hi @LQ971225 ,

Thank you for your attention of our work!
The ``edges_prefix`` represents the path of folder that stores detected edge maps from ground truth images, and we use [bdcn](https://github.com/pkuCactus/BDCN) as the edge detector. To execute the code, you need to prepare the edge maps before training. Hope our answer addresses your problem.

Best,

**Comment by LQ971225** [comment]
Thank you for your prompt reply. Can I understand that I need to run the BDCN code, and after running it, it will generate a file with the name "edges_prefix"?

**Comment by AlonzoLeeeooo** [comment]
> Thank you for your prompt reply. Can I understand that I need to run the BDCN code, and after running it, it will generate a file with the name "edges_prefix"?

The `edges_prefix` is a parameter you need to configure when you are executing the python file, e.g., `python SRN_train.py --edges_prefix edge_path`. Here are some recommended data preparation procedures, you may refer to them:
1. Download the image dataset. Assume that the images are saved at `./images`.
2. Execute the [BDCN edge detector](https://github.com/pkuCactus/BDCN) code. Assume your saved edge maps are located at `./edges`. Make sure that the detected edge map shares the same filename as its corresponding ground truth image.
3. When execute the python file, configure the `edges_prefix` parameter. An example command line may be: `python SRN_train.py --edges_prefix ./edges`.

**Comment by LQ971225** [comment]
Hello, I've been running your provided "BDCN" code in the past few days and encountered a couple of issues. Can you please assist me with these? I would greatly appreciate it! Here are the two questions:

1. When running the code, I encounter the error message: "No such file or directory 'params/bdcn_final.pth'." How can I resolve this issue?

2. In the "test.py" file, there's a line "test_root = cfg.config_test[args.dataset]['data_root']." What kind of image path should I put here?

I didn't reach out to the author of "BDCN" because they haven't provided answers to these questions. Thank you for your help!

**Comment by LQ971225** [comment]
Hi @AlonzoLeeeooo 
Sorry to bother you again. 
I really need your help. Can you please help me answer the above two questions? I would truly appreciate your assistance!

**Comment by AlonzoLeeeooo** [comment]
> Hello, I've been running your provided "BDCN" code in the past few days and encountered a couple of issues. Can you please assist me with these? I would greatly appreciate it! Here are the two questions:
> 
> 1. When running the code, I encounter the error message: "No such file or directory 'params/bdcn_final.pth'." How can I resolve this issue?
> 2. In the "test.py" file, there's a line "test_root = cfg.config_test[args.dataset]['data_root']." What kind of image path should I put here?
> 
> I didn't reach out to the author of "BDCN" because they haven't provided answers to these questions. Thank you for your help!

Sorry for the late response. Hope the following answers still help you.
1. The error message shows that you need to put the pre-trained model weights of `BDCN` in the suggested directory `params/bdcn_final.pth`. You may refer to the repository of `BDCN` to download their model weights.
2. I remember that the `--data_root` configuration of the BDCN code refers to the path that stores all your images, you may give it a shot. Please forgive if I have figure this wrong.

If you have any further question, please feel free to ask us here.
Best,

**Comment by SHIJILIANG01** [comment]
Hello, did you run the BDCN code successfully?

**Comment by AlonzoLeeeooo** [comment]
> Hello, did you run the BDCN code successfully?

Hi @SHIJILIANG01 and @LQ971225 ,

Thank you for your interests in our work! We are sorry that we haven't yet updated the code and documents of SketchRefiner due to busy schedule. Code, dataset, model weights, documents will be soon updated and refined. We will notice you as soon as everything is ready.

As for the use of BDCN, you can refer to another work of ours in [this repo](https://github.com/AlonzoLeeeooo/LCDG), which also uses BDCN for data pre-processing. We offer detailed instructions in [this document](https://github.com/AlonzoLeeeooo/LCDG/tree/main/data-preprocessing) and pre-trained model weights of BDCN in our [Huggingface repo](https://huggingface.co/AlonzoLeeeooo/LaCon/tree/main/data-preprocessing).

Please do not hesitate to contact us if you have any further questions of our work.

Best regards
