### ISSUE TITLE
About final results

### ISSUE THREAD

**Issue by YouXMu** [AlonzoLeeeooo/SketchRefiner#5]
Hi, I noticed that there are two outputs at the end of SIN_test, one is 'inpainted_with_sketch' and the other is 'inpainted_with_refined_sketch ', so which one should I choose as the final fix result? Also, may I ask you what is the approximate parameter count of the model for this work?

**Comment by AlonzoLeeeooo** [comment]
Hi @YouXMu ,

Thank you for your attention of our work! `inpainted_with_sketch` and `inpainted_with_refined_sketch` correspond to the configurations `--sketches` and `--refined_sketches`, respectively. We set this to directly show the difference w/ or w/o sketch refinement.

For the final result, referring to `inpainted_with_refined_sketch` will be alright.

As for the model parameters, our overall pipeline has approximately 38M model parameters. We reported this in Tab. XI of our [TMM 2024 paper](https://ieeexplore.ieee.org/abstract/document/10533842). If you are interested, please refer to the paper for more details.

If you have any further questions about our work, please do not hesitate to leave a message in this issue!

Best regards
