### ISSUE TITLE
About custom mask areas

### ISSUE THREAD

**Issue by YouXMu** [AlonzoLeeeooo/SketchRefiner#6]
Hi, I noticed that  there are some custom masks for landscapes and faces in the paper . How do I get the custom masks I want? Can you give me some suggestions? Thanks!

**Comment by AlonzoLeeeooo** [comment]
Hi @YouXMu,

We use external softwares, e.g., iPad SketchBook App and Windows Drawings, to get customed masks. Hope these solutions can address your demands.

Best

**Comment by AlonzoLeeeooo** [comment]
Hi @YouXMu ,

If you have any further questions, please do not hesitate to leave a message in this issue. This issue will be closed for now.

Best
