### ISSUE TITLE
alternative url for pretrained weight

### ISSUE THREAD

**Issue by JEONG8652** [AlonzoLeeeooo/SketchRefiner#7]
Hello, Thank you for your great work.

I would like to try demo for your SketchRefiner, but It is very hard to download the pretrained weights from Baidu cloud since I am living outside China.
would you mind uploading the weight file and Real-World Test Protocol to an alternative drive (Google Drive or OneDrive)?

Thank you.

**Comment by AlonzoLeeeooo** [comment]
Hi @JEONG8652 ,

Thank you for your attention! We will try uploading the model weights and real-world test protocol to a Google Drive link recently. Once the link is ready, we will share the link with you in this issue. Please notice our messages.

Best regards

**Comment by AlonzoLeeeooo** [comment]
Hi @JEONG8652 ,

We have uploaded pre-trained models and the real-world test protocol in a Google Drive as well as a Huggingface repo. Please check if it is okay for you to download them. The links are listed as follows:
- [Google Drive](https://drive.google.com/drive/folders/1xOeKO4f6tfco2AV0V_0EgJzYThOFb3kp?usp=drive_link)
- Huggingface: [(models)](https://huggingface.co/AlonzoLeeeooo/SketchRefiner) [(test protocol)](https://huggingface.co/datasets/AlonzoLeeeooo/sketchrefiner-real-world-test-protocol)

If you have any further questions, please do not hesitate to contact us in this issue.

Best regards
