### ISSUE TITLE
作者你好，我现在想复现这篇代码，直接下载代码可以吗，还是等您这边更新完后才可以

### ISSUE THREAD

**Issue by liuna0211** [AlonzoLeeeooo/SketchRefiner#8]

**Comment by AlonzoLeeeooo** [comment]
您好，感谢关注我们的工作！您可以直接用我们的代码，ICCV投稿版本的代码是可以运行的，只是在部分网络名上有区别，具体区别如下（左边是ICCV版本，右边是TMM版本）：
- `Sketch Simulation Algorithm (SSA)`对应：`Deformable Sketch Simulation (DSS)`
- `Sketch Refinement Network`基本一致
- `Cross-Corrleation Loss`对应：`Cross Region Correlation (CRC)`
- `Partial Sketch Encoder (PSE)`对应：`Latent Sketch Aligner (LSA)`
- `Texture Restoration Module (TRM)`对应：`Sketch Conditional Inpaintor (SCI)`
- `Sketch Feature Aggregation (SFA)`基本一致

目前我们还需要一段时间整理代码，因此短期内代码暂时不会有大改动。之前我们的[模型权重](https://huggingface.co/AlonzoLeeeooo/SketchRefiner)和[测试集](https://huggingface.co/datasets/AlonzoLeeeooo/sketchrefiner-real-world-test-protocol)也是开源的，您这边有需要可以到我们的HuggingFace repo下载。

关于我们工作的细节如果您有其他的问题，请您随时在这个issue下继续联系我们，谢谢！

祝好

**Comment by liuna0211** [comment]
我在使用BDCN获取celeba-hq边缘图的时候，代码很多报错，没有标签等等，作者有没有其他推荐哇呜呜

**Comment by AlonzoLeeeooo** [comment]
> 我在使用BDCN获取celeba-hq边缘图的时候，代码很多报错，没有标签等等，作者有没有其他推荐哇呜呜

BDCN其实属于HED类的edge，如果你对HED更熟悉也可以用HED，根据我们的经验的话，BDCN提取的edge细节更多。

关于BDCN的代码，官方实现是[这个repo](https://github.com/pkuCactus/BDCN)（个人不推荐，用的是python 2实现）。我更推荐你使用我[另一个repo](https://github.com/AlonzoLeeeooo/LCDG)的实现（在`data-preprocessing/bdcn-edge-detection`中），code我已经改成python 3的了，具体怎样跑可以参考下面这个命令行，改一下路径即可，BDCN的模型权重你可以在我的[这个HuggingFace repo](https://huggingface.co/AlonzoLeeeooo/LaCon)中下载（`data-preprocessing/bdcn.pth`）：
```bash
python generate-bdcn-edge.py --indir IMAGE_PATH --outdir HED_EDGE_PATH
```

**Comment by liuna0211** [comment]
非常非常感谢您的回复，我开始研究这个

**Comment by AlonzoLeeeooo** [comment]
> 非常非常感谢您的回复，我开始研究这个

不客气的～有什么问题欢迎随时联系我们！

**Comment by liuna0211** [comment]
您建议我们加个联系方式吗，我害怕到时候这下面都是我的问题

**Comment by AlonzoLeeeooo** [comment]
> 您建议我们加个联系方式吗，我害怕到时候这下面都是我的问题

没关系，在issue里面讨论吧～我只要看到都会回复的，这样其他有类似问题的朋友也可以参与进来～

**Comment by AlonzoLeeeooo** [comment]
@liuna0211 您好，关于我们的工作您这边暂时没有其他问题的话，这个issue就先暂时关闭了哈～后续如果您有其他问题，欢迎随时在这个issue底下留言，或者[提出一个新issue](https://github.com/AlonzoLeeeooo/SketchRefiner/issues/new)联系我们～
